# Generated by Django 4.0 on 2021-12-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_student_options_std_teach'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.DeleteModel(
            name='Std_teach',
        ),
        migrations.AddField(
            model_name='studentposition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='school.student'),
        ),
        migrations.AddField(
            model_name='studentposition',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='school.teacher'),
        ),
    ]
